"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Bookmark, CalendarDays, ChevronLeft, ChevronRight, Download, ExternalLink, GripVertical, LayoutDashboard, Lock, Maximize2, Minimize2, Move, RefreshCw, Search, Star, X } from "lucide-react";
import seedData from "../../data/latest.json";
import { aiChainRows, assetScores, correlation, eventRows, fallbackHistory, lastChange, macroRegime, navigation, newsSummaryZh, returns, type DashboardData, type HistorySeries } from "../lib/dashboard";

const sectionTitles: Record<string,[string,string]>={overview:["全球资产配置驾驶舱","风险、宏观、轮动与事件的一页晨会结论"],allocation:["资产配置打分","把跨资产行情转化为可执行的风险偏好判断"],regime:["宏观 Regime 四象限","增长与通胀方向决定资产配置主线"],correlation:["相关性与轮动矩阵","识别分散化是否失效，以及跨资产共振"],markets:["全球市场快照","权益、利率、商品、汇率与AI主题横向比较"],"etf-flows":["ETF资金与成交动能","区分成交代理与真实净申赎口径"],"ai-chain":["AI产业链深度监控","从算力、云、电力到应用和材料的全链条信号"],calendar:["全球事件日历","按日期追踪政策、通胀、就业、能源与中国宏观"],research:["数据与新闻研究台","结构化宏观数据、模型价格与可回溯原文"],workspace:["我的分析工作区","收藏资产并保存个人晨会布局"],report:["今日资产配置晨报","汇总行情、宏观、AI链条与风险提示"]};
type FavoriteItem={id:string;label:string;code:string;category:string;href:string;keywords:string};
const FAVORITES_KEY="aa-favorites-v2";
const assetFavoriteCatalog:FavoriteItem[]=[
  {id:"asset:nvda",label:"英伟达",code:"NVDA",category:"AI芯片",href:"/ai-chain",keywords:"英伟达 NVIDIA GPU 算力 AI"},
  {id:"asset:gold",label:"黄金",code:"GLD",category:"贵金属",href:"/markets",keywords:"黄金 金价 贵金属 gold"},
  {id:"rate:us10y",label:"美国10年期国债收益率",code:"US10Y",category:"利率",href:"/regime",keywords:"美债 十年期 国债收益率 美国利率"},
  {id:"asset:csi300",label:"沪深300ETF",code:"ASHR",category:"A股",href:"/markets",keywords:"沪深 沪深300 A股 中国股票 ETF"},
  {id:"asset:sp500",label:"标普500ETF",code:"SPY",category:"美股",href:"/markets",keywords:"标普 标普500 S&P500 美国股票"},
  {id:"asset:hongkong",label:"香港市场ETF",code:"EWH",category:"港股",href:"/markets",keywords:"恒生 港股 香港股票"},
  {id:"asset:usd",label:"美元指数代理",code:"UUP",category:"外汇",href:"/markets",keywords:"美元 美元指数 DXY 外汇"},
  {id:"asset:ust",label:"美国长久期国债",code:"TLT",category:"债券",href:"/markets",keywords:"美债 美国国债 长债 久期"},
  {id:"asset:copper",label:"铜ETF",code:"CPER",category:"工业金属",href:"/markets",keywords:"铜 铜价 工业金属 商品"},
  {id:"asset:oil",label:"原油ETF",code:"USO",category:"能源",href:"/markets",keywords:"原油 油价 WTI 能源 商品"},
  {id:"asset:ai",label:"全球AI与机器人ETF",code:"BOTZ",category:"AI主题",href:"/ai-chain",keywords:"AI 人工智能 机器人 算力"},
  {id:"event:fomc",label:"FOMC议息会议",code:"FOMC",category:"宏观事件",href:"/calendar",keywords:"美联储 议息会议 利率决议"},
  {id:"event:cpi",label:"美国CPI",code:"CPI",category:"宏观事件",href:"/calendar",keywords:"通胀 美国消费者价格"},
  {id:"event:nfp",label:"美国非农就业",code:"NFP",category:"宏观事件",href:"/calendar",keywords:"非农 就业 美国劳动力"},
  {id:"event:eia",label:"EIA原油库存",code:"EIA",category:"能源事件",href:"/calendar",keywords:"原油库存 能源 EIA"}
];
const pageFavoriteCatalog:FavoriteItem[]=navigation.map(item=>({id:`page:${item.key}`,label:item.label,code:"分析页",category:"研究模块",href:item.href,keywords:`${item.label} ${sectionTitles[item.key]?.join(" ")??""}`}));
const favoriteCatalog=[...assetFavoriteCatalog,...pageFavoriteCatalog];
const defaultFavoriteIds=["asset:nvda","asset:gold","rate:us10y","asset:csi300"];
const favoriteMatches=(item:FavoriteItem,value:string)=>`${item.label} ${item.code} ${item.category} ${item.keywords}`.toLowerCase().includes(value.trim().toLowerCase());
const findFavorite=(value:string)=>favoriteCatalog.find(item=>item.id===value||item.label===value||item.code.toLowerCase()===value.toLowerCase())??favoriteCatalog.find(item=>favoriteMatches(item,value));
const loadFavorites=()=>{try{const current=JSON.parse(localStorage.getItem(FAVORITES_KEY)||"null");if(Array.isArray(current)){const valid=current.map(item=>typeof item==="string"?findFavorite(item):findFavorite(String(item?.id??item?.label??""))).filter(Boolean) as FavoriteItem[];if(valid.length||current.length===0)return valid}const legacy=JSON.parse(localStorage.getItem("aa-favorites")||"null");if(Array.isArray(legacy)){const migrated=legacy.map(item=>findFavorite(String(item))).filter(Boolean) as FavoriteItem[];if(migrated.length){localStorage.setItem(FAVORITES_KEY,JSON.stringify(migrated));return migrated}}}catch{}return defaultFavoriteIds.map(id=>findFavorite(id)!).filter(Boolean)};
const formatNumber=(value:unknown,digits=2)=>{const n=Number(value);return Number.isFinite(n)?n.toLocaleString("zh-CN",{maximumFractionDigits:digits}):"-"};
const pct=(value:unknown)=>{const n=Number(value);return Number.isFinite(n)?`${n>=0?"+":""}${n.toFixed(2)}%`:"-"};
const compactMoney=(value:unknown)=>{if(value===null||value===undefined)return "建立基线";const n=Number(value);if(!Number.isFinite(n))return "建立基线";const sign=n>=0?"+":"-",absolute=Math.abs(n);return `${sign}$${absolute>=1e9?(absolute/1e9).toFixed(2)+"B":(absolute/1e6).toFixed(1)+"M"}`};
const tone=(value:number)=>value>0?"up":value<0?"down":"flat";

function StatusPill({children,kind="neutral"}:{children:React.ReactNode;kind?:string}){return <span className={`status-pill ${kind}`}>{children}</span>}
function Panel({title,kicker,children,action,className=""}:{title:string;kicker?:string;children:React.ReactNode;action?:React.ReactNode;className?:string}){return <section className={`terminal-panel ${className}`}><header className="panel-head"><div>{kicker&&<span>{kicker}</span>}<h2>{title}</h2></div>{action}</header>{children}</section>}
function MiniLine({series}:{series:HistorySeries}){const p=series.points.slice(-40),min=Math.min(...p.map(i=>i.close)),max=Math.max(...p.map(i=>i.close)),coords=p.map((i,x)=>`${x/Math.max(1,p.length-1)*100},${34-(i.close-min)/Math.max(.001,max-min)*30}`).join(" ");return <svg className="mini-line" viewBox="0 0 100 36" preserveAspectRatio="none"><polyline points={coords}/></svg>}

function ScoreBoard({data,history}:{data:DashboardData;history:HistorySeries[]}){return <><details className="score-method"><summary>评分说明</summary><div><strong>这是相对配置分，不是考试分数。</strong><span>综合20日价格动量、利率、信用利差及代表性龙头日度强弱，先形成原始信号，再按当期八类资产横向强弱映射至62–88分。</span><span>85–88 强超配 · 79–84 超配 · 73–78 中性 · 67–72 谨慎 · 62–66 低配。分数用于比较，不代表收益保证。</span></div></details><div className="score-grid">{assetScores(data,history).map(item=><Link className="score-card" href={item.asset==="AI"?"/ai-chain":"/markets"} key={item.asset}><div className="score-top"><strong>{item.asset}</strong><StatusPill kind={item.score>=79?"positive":item.score<67?"negative":"neutral"}>{item.view}</StatusPill></div><div className="score-number">{item.score}<small>/100</small></div><div className="score-track"><i style={{width:`${item.score}%`}}/></div><p>{item.driver}</p></Link>)}</div></>}

function RegimeBoard({data}:{data:DashboardData}){const regime=macroRegime(data),cells=[{name:"再通胀",growth:"增长上行",inflation:"通胀上行",assets:"股票 · 商品 · 铜"},{name:"金发姑娘",growth:"增长上行",inflation:"通胀下行",assets:"股票 · AI · 信用债"},{name:"滞胀",growth:"增长下行",inflation:"通胀上行",assets:"黄金 · 能源 · 防御"},{name:"衰退/通缩",growth:"增长下行",inflation:"通胀下行",assets:"美债 · 美元 · 黄金"}];return <><div className="regime-axis-label">通胀方向</div><div className="regime-grid">{cells.map(cell=><div className={`regime-cell ${regime.quadrant===cell.name?"active":""}`} key={cell.name}><div><span>{cell.growth}</span><span>{cell.inflation}</span></div><strong>{cell.name}</strong><p>{cell.assets}</p></div>)}</div><div className="regime-summary"><div><span>当前判定</span><strong>{regime.quadrant}</strong></div><div><span>优先关注</span><strong>{regime.focus}</strong></div><div><span>相对回避</span><strong>{regime.avoid}</strong></div></div></>}

function CorrelationMatrix({history,days}:{history:HistorySeries[];days:number}){const visible=history.filter(i=>["A股","美股","黄金","美元","美债","铜","原油"].includes(i.label));return <div className="matrix-wrap"><table className="matrix-table"><thead><tr><th>{days}日</th>{visible.map(i=><th key={i.label}>{i.label}</th>)}</tr></thead><tbody>{visible.map(row=><tr key={row.label}><th>{row.label}</th>{visible.map(column=>{const value=row.label===column.label?1:correlation(returns(row,days),returns(column,days)),alpha=Math.abs(value)*.82+.08;return <td key={column.label} style={{background:value>=0?`rgba(177,24,57,${alpha})`:`rgba(24,109,122,${alpha})`,color:Math.abs(value)>.46?"white":"#22191b"}}>{value.toFixed(2)}</td>})}</tr>)}</tbody></table></div>}

function MarketsTable({data,history}:{data:DashboardData;history:HistorySeries[]}){const bySymbol=new Map((data.fmp_quotes??[]).map(i=>[i.symbol,i]));return <div className="data-table"><div className="table-row table-head"><span>资产</span><span>代码</span><span>最新</span><span>1日</span><span>20日</span><span>60日趋势</span><span>来源</span></div>{history.map(series=>{const quote=bySymbol.get(series.symbol),price=quote?.price??series.points.at(-1)?.close,daily=quote?.change_pct??lastChange(series),twenty=lastChange(series,20);return <div className="table-row" key={series.symbol}><span><strong>{series.label}</strong><small>{series.name}</small></span><span className="mono">{series.symbol}</span><span className="mono">{formatNumber(price)}</span><span className={tone(daily??0)}>{pct(daily)}</span><span className={tone(twenty)}>{pct(twenty)}</span><span><MiniLine series={series}/></span><a href={series.url} target="_blank" rel="noreferrer">{series.source}<ExternalLink size={12}/></a></div>})}</div>}

function OverviewPage({data,history}:{data:DashboardData;history:HistorySeries[]}){const scores=assetScores(data,history),regime=macroRegime(data),events=eventRows(data),nextHigh=events.find(item=>item.importance==="高")??events[0],sorted=scores.slice().sort((a,b)=>b.score-a.score),riskAvg=scores.filter(i=>["股票","商品","AI","港股","A股"].includes(i.asset)).reduce((s,i)=>s+i.score,0)/5;return <><div className="decision-strip"><div><span>风险偏好</span><strong>{riskAvg>=77?"偏强":riskAvg<70?"偏弱":"中性"}</strong></div><div><span>宏观象限</span><strong>{regime.quadrant}</strong></div><div><span>最强资产</span><strong>{sorted[0].asset} {sorted[0].score}</strong></div><div><span>最弱资产</span><strong>{sorted.at(-1)!.asset} {sorted.at(-1)!.score}</strong></div><div><span>下一高影响事件</span><strong>{nextHigh?`${nextHigh.date.slice(5)} ${nextHigh.event}`:"待官方更新"}</strong></div></div><div className="page-grid"><Panel title="资产配置打分" kicker="CROSS-ASSET SCORE" className="span-2" action={<Link className="text-action" href="/allocation">查看模型<ChevronRight size={14}/></Link>}><ScoreBoard data={data} history={history}/></Panel><Panel title="宏观四象限" kicker="MACRO REGIME" action={<Link className="text-action" href="/regime">展开<ChevronRight size={14}/></Link>}><RegimeBoard data={data}/></Panel><Panel title="20日相关性" kicker="CORRELATION" className="span-2" action={<Link className="text-action" href="/correlation">20/60日切换<ChevronRight size={14}/></Link>}><CorrelationMatrix history={history} days={20}/></Panel><Panel title="未来事件" kicker="EVENT WATCH"><div className="event-stack">{events.slice(0,4).map(item=><Link href="/calendar" key={item.date+item.event}><time>{item.date.slice(5)}</time><span><strong>{item.event}</strong><small>{item.assets}</small></span><StatusPill kind={item.importance==="高"?"negative":"neutral"}>{item.importance}</StatusPill></Link>)}</div></Panel><Panel title="市场轮动" kicker="GLOBAL ROTATION" className="span-3"><MarketsTable data={data} history={history.slice(0,6)}/></Panel></div></>}

function AllocationPage({data,history}:{data:DashboardData;history:HistorySeries[]}){const scores=assetScores(data,history),riskScores=scores.filter(i=>["股票","商品","AI","港股","A股"].includes(i.asset)),avg=Math.round(riskScores.reduce((s,i)=>s+i.score,0)/riskScores.length),backtest=data.score_backtest??[];return <div className="page-grid"><Panel title="八类资产配置温度" kicker="ALLOCATION SCORE" className="span-2"><ScoreBoard data={data} history={history}/></Panel><Panel title="组合风险偏好" kicker="RISK APPETITE"><div className="dial"><strong>{avg}</strong><span>{avg>=77?"风险偏好偏强":avg<70?"风险偏好偏弱":"风险偏好中性"}</span></div><div className="insight-list">{scores.slice().sort((a,b)=>b.score-a.score).slice(0,3).map((item,index)=><div key={item.asset}><em>0{index+1}</em><span><strong>{item.asset} {item.view}</strong><small>{item.driver}</small></span></div>)}</div></Panel><Panel title="历史校准与回测" kicker="MODEL VALIDATION" className="span-3"><details className="score-method"><summary>回测口径</summary><div><strong>只检验价格子模型，不把宏观数据事后填回历史。</strong><span>当60日内技术信号位于自身历史前40%时，观察随后20个交易日收益；所有信号仅使用当时及以前的数据。</span><span>样本目前约6个月，结果用于校准而非收益承诺；随着每日更新，样本会自动扩展。</span></div></details><div className="data-table backtest-table"><div className="table-row table-head"><span>资产</span><span>代理</span><span>20日命中率</span><span>信号后均值</span><span>区间最大回撤</span><span>当前历史分位</span><span>有效样本</span></div>{backtest.map(item=><div className="table-row" key={item.asset}><strong>{item.asset}</strong><span className="mono">{item.symbol}</span><span>{item.hit_rate_20d===null?"建立样本":`${formatNumber(item.hit_rate_20d,1)}%`}</span><span className={tone(item.avg_forward_return_20d??0)}>{item.avg_forward_return_20d===null?"-":pct(item.avg_forward_return_20d)}</span><span className="down">{formatNumber(item.max_drawdown,1)}%</span><span>{formatNumber(item.current_percentile,0)}%</span><span>{item.sample_size}</span></div>)}</div></Panel></div>}

function RegimePage({data}:{data:DashboardData}){return <div className="page-grid"><Panel title="增长 × 通胀定位" kicker="REGIME MAP" className="span-2"><RegimeBoard data={data}/></Panel><Panel title="判定因子" kicker="MODEL INPUTS"><div className="factor-list">{(data.fred_macro??[]).map(item=><a href={item.url} target="_blank" rel="noreferrer" key={item.series_id}><span>{item.name}<small>{item.date}</small></span><strong>{formatNumber(item.value,3)}</strong><em className={tone(item.change??0)}>{formatNumber(item.change,3)}</em></a>)}</div></Panel><Panel title="象限资产映射" kicker="PLAYBOOK" className="span-3"><div className="playbook-grid">{[["再通胀","超配：股票、商品、铜","低配：长久期债券"],["金发姑娘","超配：股票、AI、信用债","低配：美元现金"],["滞胀","超配：黄金、能源、防御","低配：成长与长债"],["衰退/通缩","超配：美债、美元、黄金","低配：周期与高收益债"]].map(row=><div key={row[0]}><strong>{row[0]}</strong><span>{row[1]}</span><small>{row[2]}</small></div>)}</div></Panel></div>}

function CorrelationPage({history}:{history:HistorySeries[]}){const[days,setDays]=useState(20);return <div className="page-grid"><Panel title="跨资产相关性矩阵" kicker="ROLLING CORRELATION" className="span-3" action={<div className="segmented"><button className={days===20?"active":""} onClick={()=>setDays(20)}>20日</button><button className={days===60?"active":""} onClick={()=>setDays(60)}>60日</button></div>}><CorrelationMatrix history={history} days={days}/><div className="matrix-legend"><span><i className="positive"/>正相关</span><span><i className="negative"/>负相关</span><small>使用ETF日收益率滚动计算，数值越接近 ±1 联动越强。</small></div></Panel><Panel title="轮动强弱" kicker="RELATIVE MOMENTUM" className="span-2"><div className="rotation-bars">{history.map(item=>({label:item.label,value:lastChange(item,days)})).sort((a,b)=>b.value-a.value).map(item=><div key={item.label}><span>{item.label}</span><div><i className={tone(item.value)} style={{width:`${Math.min(100,Math.abs(item.value)*6+8)}%`}}/></div><strong className={tone(item.value)}>{pct(item.value)}</strong></div>)}</div></Panel><Panel title="分散化提示" kicker="PORTFOLIO NOTE"><p className="large-note">当股债相关性同步转正、美元与黄金同涨时，传统分散化可能失效。当前矩阵用于快速识别组合中隐藏的同向暴露。</p></Panel></div>}

function EtfPage({data,history}:{data:DashboardData;history:HistorySeries[]}){
  const quoteMap=new Map((data.fmp_quotes??[]).map(i=>[i.symbol,i])),etfs=history.filter(i=>["SPY","ASHR","EWH","GLD","TLT","CPER","USO","BOTZ"].includes(i.symbol));
  const flows=data.etf_fund_flows??[],computed=flows.filter(item=>item.estimated_flow!==null),totalFlow=computed.reduce((sum,item)=>sum+(item.estimated_flow??0),0);
  return <div className="page-grid">
    <Panel title="ETF资金温度" kicker="FLOW & LIQUIDITY" className="span-3"><div className="data-table etf-table"><div className="table-row table-head"><span>ETF</span><span>资产</span><span>价格</span><span>日涨跌</span><span>20日动量</span><span>成交量</span><span>口径</span></div>{etfs.map(item=>{const q=quoteMap.get(item.symbol);return <div className="table-row" key={item.symbol}><span><strong>{item.symbol}</strong><small>{item.name}</small></span><span>{item.label}</span><span className="mono">{formatNumber(q?.price??item.points.at(-1)?.close)}</span><span className={tone(q?.change_pct??lastChange(item))}>{pct(q?.change_pct??lastChange(item))}</span><span className={tone(lastChange(item,20))}>{pct(lastChange(item,20))}</span><span className="mono">{q?.volume?formatNumber(q.volume/1e6,1)+"M":"价格代理"}</span><StatusPill kind="warning">成交动能</StatusPill></div>})}</div></Panel>
    <Panel title="发行商份额与净申赎估算" kicker="PRIMARY MARKET FLOW" className="span-3"><div className="flow-metrics"><div><span>官方份额覆盖</span><strong>{flows.length} / 8</strong><small>核心ETF已接入发行商官网</small></div><div><span>最新可计算净申赎</span><strong className={tone(totalFlow)}>{computed.length?compactMoney(totalFlow):"建立基线"}</strong><small>{computed.length?`${computed.length}只ETF合计`:"下一不同交易日生成变化"}</small></div><div><span>机构资金拆分</span><strong>商业数据</strong><small>持有人维度仍需 Choice / Wind</small></div></div><div className="data-table official-flow-table"><div className="table-row table-head"><span>ETF / 资产</span><span>NAV</span><span>流通份额</span><span>份额变化</span><span>变化率</span><span>估算净申赎</span><span>数据日</span><span>官方来源</span></div>{flows.map(item=><div className="table-row" key={item.symbol}><span><strong>{item.symbol}</strong><small>{item.asset} · {item.issuer}</small></span><span className="mono">${formatNumber(item.nav)}</span><span className="mono">{item.shares_outstanding?formatNumber(item.shares_outstanding/1e6,2)+"M":"-"}</span><span className={tone(item.shares_change??0)}>{item.shares_change===null?"建立基线":`${item.shares_change>=0?"+":""}${formatNumber(item.shares_change/1e6,2)}M`}</span><span className={tone(item.shares_change_pct??0)}>{item.shares_change_pct===null?"-":pct(item.shares_change_pct)}</span><strong className={tone(item.estimated_flow??0)}>{compactMoney(item.estimated_flow)}</strong><span>{item.as_of}</span><a href={item.url} target="_blank" rel="noreferrer">{item.issuer}<ExternalLink size={12}/></a></div>)}</div></Panel>
    <Panel title="口径说明" kicker="DATA DISCIPLINE" className="span-3"><p className="large-note">净申赎估算 = 相邻两个交易日的发行商官方流通份额变化 × 当日 NAV。它比成交额更接近 ETF 一级市场真实创建/赎回，但不代表二级市场主动买卖，也不能拆分具体机构。当前覆盖 SPY、GLD、TLT、EWH、BOTZ；其余品种继续使用成交动能，避免把不可靠数据伪装成资金流。</p></Panel>
  </div>
}

function AiPage({data}:{data:DashboardData}){
  const pricingTime=data.pricing_generated_at?new Date(data.pricing_generated_at).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai"}):"随4H数据更新",chain=aiChainRows(data);
  return <div className="page-grid">
    <Panel title="AI全链条景气表" kicker="AI VALUE CHAIN" className="span-3"><div className="data-table chain-table"><div className="table-row table-head"><span>环节</span><span>细分</span><span>样本 / 龙头</span><span>平均涨跌</span><span>上涨家数</span><span>相对量</span><span>PE中位数</span><span>强度</span></div>{chain.map(item=><div className="table-row" key={item.group}><StatusPill kind={item.segment==="上游"?"negative":item.segment==="中游"?"warning":"neutral"}>{item.segment}</StatusPill><strong>{item.group}</strong><span className="mono">{item.sample_size??"-"}只 · {item.leaders}</span><span className={tone(item.change)}>{pct(item.change)}</span><span>{item.breadth===undefined?"-":`${formatNumber(item.breadth,0)}%`}</span><span>{item.relative_volume===undefined?"-":`${formatNumber(item.relative_volume,2)}x`}</span><span>{item.valuation_pe?`${formatNumber(item.valuation_pe,1)}x`:"-"}</span><span><b className="strength" style={{"--strength":`${item.strength}%`} as React.CSSProperties}>{item.strength}</b></span></div>)}</div></Panel>
    <Panel title="AI产业链景气排名" kicker="CHAIN SIGNAL" className="span-3"><details className="chain-method"><summary>排名口径</summary><div>强度由代表成分股当日平均涨跌、上涨家数占比、成交量相对20日均量及PE中位数自动计算。缺失估值不做惩罚，排名是研究优先级而非个股推荐。</div></details><div className="chain-ranking">{chain.slice().sort((a,b)=>b.strength-a.strength).map((item,index)=><div key={item.group}><em>{String(index+1).padStart(2,"0")}</em><span><strong>{item.group}<b>{item.strength}</b></strong><small>{item.segment} · 成分 {item.constituents??item.leaders}</small><p>{item.signal}</p></span></div>)}</div></Panel>
    <Panel title="全球大模型Token价格" kicker="MODEL ECONOMICS" className="span-3" action={<span className="pricing-updated">更新于 {pricingTime}</span>}><div className="model-price-note">价格单位：美元 / 100万Token；采用厂商官方标准API价格，长上下文、批处理、区域部署及工具调用可能另行计费。</div><div className="data-table model-price-table"><div className="table-row table-head"><span>厂商</span><span>模型</span><span>计价口径 / 上下文</span><span>输入</span><span>缓存输入</span><span>输出</span><span>适用方向</span><span>状态 / 来源</span></div>{(data.ai_model_pricing??[]).map(item=><a className="table-row" href={String(item.url)} target="_blank" rel="noreferrer" key={String(item.provider)+String(item.model)}><strong>{String(item.provider)}</strong><span className="mono">{String(item.model)}</span><small>{String(item.context)}</small><span className="mono price-cell">{String(item.input_per_m)}</span><span className="mono">{String(item.cached_input_per_m??"—")}</span><span className="mono price-cell">{String(item.output_per_m)}</span><small>{String(item.focus)}</small><span className="price-source"><StatusPill kind={String(item.price_status)==="官方实时"?"positive":"neutral"}>{String(item.price_status??"官方基准")}</StatusPill><ExternalLink size={12}/></span></a>)}</div></Panel>
  </div>
}

function CalendarPage({data}:{data:DashboardData}){
  const today=new Date(),todayStart=new Date(today.getFullYear(),today.getMonth(),today.getDate()),windowEnd=new Date(todayStart);windowEnd.setDate(windowEnd.getDate()+30);
  const events=eventRows(data);
  const [calendarOpen,setCalendarOpen]=useState(false),[selectedDate,setSelectedDate]=useState<string|null>(null),[visibleMonth,setVisibleMonth]=useState(()=>new Date(today.getFullYear(),today.getMonth(),1));
  const highEventCount=events.filter(item=>{const d=new Date(`${item.date}T00:00:00`);return item.importance==="高"&&d>=todayStart&&d<=windowEnd}).length;
  const year=visibleMonth.getFullYear(),month=visibleMonth.getMonth(),leading=new Date(year,month,1).getDay(),daysInMonth=new Date(year,month+1,0).getDate(),cells=Array.from({length:leading+daysInMonth},(_,index)=>index<leading?null:index-leading+1);
  const monthLabel=new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"long"}).format(visibleMonth);
  const closeCalendar=(clear=true)=>{setCalendarOpen(false);if(clear)setSelectedDate(null)};
  const chooseDate=(date:string)=>{setSelectedDate(date);setCalendarOpen(false);setTimeout(()=>document.getElementById(`event-${date}`)?.scrollIntoView({behavior:"smooth",block:"center"}),40)};
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape")closeCalendar()};document.addEventListener("keydown",onKey);return()=>document.removeEventListener("keydown",onKey)},[]);
  return <div className="page-grid calendar-page" onClick={event=>{const target=event.target as HTMLElement;if(selectedDate&&!calendarOpen&&!target.closest(".calendar-list a")&&!target.closest(".calendar-trigger"))setSelectedDate(null)}}>
    <Panel title="未来高影响事件" kicker="EVENT CALENDAR" className="span-2"><div className="calendar-list">{events.map(item=><a id={`event-${item.date}`} className={selectedDate===item.date?"selected":""} href={item.source} target="_blank" rel="noreferrer" key={item.date+item.event}><time><strong>{item.date.slice(8)}</strong><span>{item.date.slice(0,7)}</span></time><div><span>{item.region} · {item.source_name??"官方日历"}</span><strong>{item.event}</strong><small>影响：{item.assets}</small></div><StatusPill kind={item.importance==="高"?"negative":"neutral"}>{item.importance}</StatusPill><ExternalLink size={14}/></a>)}</div></Panel>
    <Panel title="本期事件密度" kicker="RISK WINDOW"><button className="calendar-summary calendar-trigger" onClick={()=>{setVisibleMonth(new Date(today.getFullYear(),today.getMonth(),1));setCalendarOpen(true)}}><CalendarDays size={28}/><strong>{highEventCount}</strong><span>未来30天高影响事件</span><small>数字表示从今天起30个自然日内，被标记为“高影响”的宏观事件数量。点击打开月历。</small></button></Panel>
    {calendarOpen&&<div className="calendar-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)closeCalendar()}}><section className="calendar-modal" role="dialog" aria-modal="true" aria-label="全球事件月历" onMouseDown={event=>event.stopPropagation()}><header><button aria-label="上一个月" onClick={()=>setVisibleMonth(new Date(year,month-1,1))}><ChevronLeft size={18}/></button><div><span>EVENT CALENDAR</span><strong>{monthLabel}</strong></div><button aria-label="下一个月" onClick={()=>setVisibleMonth(new Date(year,month+1,1))}><ChevronRight size={18}/></button><button className="calendar-close" aria-label="关闭月历" onClick={()=>closeCalendar()}><X size={17}/></button></header><div className="calendar-weekdays">{["日","一","二","三","四","五","六"].map(day=><span key={day}>{day}</span>)}</div><div className="calendar-month-grid">{cells.map((day,index)=>{if(day===null)return <span className="calendar-empty" key={`empty-${index}`}/>;const date=`${year}-${String(month+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`,dayEvents=events.filter(item=>item.date===date),hasHigh=dayEvents.some(item=>item.importance==="高"),isToday=date===`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,"0")}-${String(today.getDate()).padStart(2,"0")}`;return <button className={`${hasHigh?"has-high":""} ${selectedDate===date?"active":""} ${isToday?"today":""}`} disabled={!dayEvents.length} onClick={()=>dayEvents.length&&chooseDate(date)} key={date}><span>{day}</span>{hasHigh&&<i/>}{dayEvents.length>0&&<small>{dayEvents.length}项</small>}</button>})}</div><footer><span><i/>高影响事件</span><small>点击带标记日期可定位至对应事件；点击月历外空白处关闭并取消选择。</small></footer></section></div>}
  </div>
}

function ResearchPage({data}:{data:DashboardData}){const news=[...(data.alpha_news??[]),...(data.gdelt_news??[])].slice(0,12);return <div className="page-grid"><Panel title="宏观数据底表" kicker="MACRO EVIDENCE" className="span-3"><div className="data-table macro-deep"><div className="table-row table-head"><span>指标</span><span>类别</span><span>最新值</span><span>前值</span><span>变化</span><span>日期</span><span>配置影响</span><span>来源</span></div>{(data.fred_macro??[]).map(item=><div className="table-row" key={item.series_id}><strong>{item.name}</strong><span>{item.category}</span><span className="mono">{formatNumber(item.value,3)}</span><span className="mono">{formatNumber(item.previous,3)}</span><span className={tone(item.change??0)}>{formatNumber(item.change,3)}</span><span>{item.date}</span><small>{item.driver}</small><a href={item.url} target="_blank" rel="noreferrer">FRED<ExternalLink size={12}/></a></div>)}</div></Panel><Panel title="大宗商品与宏观新闻" kicker="NEWS INTELLIGENCE" className="span-2"><div className="news-list">{news.map((item,index)=><a href={String(item.url)} target="_blank" rel="noreferrer" key={String(item.title)+index}><StatusPill>{String(item.theme)}</StatusPill><div><strong>{String(item.title)}</strong><p className="news-summary-zh">{newsSummaryZh(item)}</p><small>{String(item.source)} · {String(item.published_at)}</small></div><ExternalLink size={14}/></a>)}</div></Panel><Panel title="数据源状态" kicker="SOURCE HEALTH"><div className="source-list">{(data.source_status??[]).map(item=><div key={String(item.key)}><span><i className={String(item.status)==="online"?"online":"cached"}/>{String(item.key)}</span><strong>{String(item.status)}</strong><small>{String(item.latency_ms??"-")} ms</small></div>)}</div></Panel></div>}

const defaultWidgets=["资产打分","宏观象限","相关性","事件日历","AI链条","ETF动能"];
function WorkspacePage({data,history,favorites,onAddFavorite,onRemoveFavorite}:{data:DashboardData;history:HistorySeries[];favorites:FavoriteItem[];onAddFavorite:(item:FavoriteItem)=>void;onRemoveFavorite:(id:string)=>void}){
  const[widgets,setWidgets]=useState(defaultWidgets),[large,setLarge]=useState<string[]>([]),[locked,setLocked]=useState(false),[pickerOpen,setPickerOpen]=useState(false),[favoriteQuery,setFavoriteQuery]=useState("");
  useEffect(()=>{try{setWidgets(JSON.parse(localStorage.getItem("aa-widgets")||"null")||defaultWidgets);setLarge(JSON.parse(localStorage.getItem("aa-large")||"[]"))}catch{}},[]);
  const persist=(next:string[],big=large)=>{setWidgets(next);localStorage.setItem("aa-widgets",JSON.stringify(next));localStorage.setItem("aa-large",JSON.stringify(big))};
  const move=(from:number,to:number)=>{if(locked||from===to)return;const next=[...widgets],[item]=next.splice(from,1);next.splice(to,0,item);persist(next)};
  const results=favoriteCatalog.filter(item=>!favorites.some(saved=>saved.id===item.id)&&favoriteMatches(item,favoriteQuery)).slice(0,12);
  return <>
    <div className="workspace-toolbar"><div><Move size={16}/><span>拖动模块调整顺序，布局只保存在当前浏览器</span></div><button onClick={()=>setLocked(!locked)}><Lock size={15}/>{locked?"已锁定":"编辑布局"}</button></div>
    <div className="favorites-shell">
      <div className="favorites-bar"><Bookmark size={15}/><strong>收藏</strong>{favorites.length===0&&<small className="favorites-empty">尚未收藏资产或页面</small>}{favorites.map(item=><span className="favorite-chip" key={item.id}><Link className="favorite-link" href={item.href} title={`打开${item.label}`}><strong>{item.label}</strong><small>{item.code} · {item.category}</small></Link><button aria-label={`移除${item.label}`} title="移除收藏" onClick={()=>onRemoveFavorite(item.id)}><X size={13}/></button></span>)}<button className={pickerOpen?"active":""} aria-expanded={pickerOpen} onClick={()=>setPickerOpen(value=>!value)}>+ 添加</button></div>
      {pickerOpen&&<div className="favorite-picker"><div className="favorite-picker-search"><Search size={16}/><input autoFocus value={favoriteQuery} onChange={event=>setFavoriteQuery(event.target.value)} placeholder="搜索 NVDA、黄金、沪深300、FOMC…"/><button aria-label="关闭收藏搜索" onClick={()=>{setPickerOpen(false);setFavoriteQuery("")}}><X size={15}/></button></div><div className="favorite-results">{results.map(item=><button onClick={()=>{onAddFavorite(item);setFavoriteQuery("")}} key={item.id}><span><strong>{item.label}</strong><small>{item.code} · {item.category}</small></span><span>{item.href.includes("calendar")?"事件日历":item.href.includes("ai-chain")?"AI产业链":item.href.includes("markets")?"全球市场":"分析模块"}<ChevronRight size={14}/></span></button>)}{results.length===0&&<div className="favorite-no-result"><Search size={18}/><strong>未找到可收藏项目</strong><small>可尝试输入代码、中文名称、资产类别或事件名称。</small></div>}</div></div>}
    </div>
    <div className="workspace-grid">{widgets.map((widget,index)=><section className={`workspace-widget ${large.includes(widget)?"large":""}`} draggable={!locked} onDragStart={e=>e.dataTransfer.setData("text/plain",String(index))} onDragOver={e=>e.preventDefault()} onDrop={e=>move(Number(e.dataTransfer.getData("text/plain")),index)} key={widget}><header><span><GripVertical size={15}/>{widget}</span><button onClick={()=>{const next=large.includes(widget)?large.filter(x=>x!==widget):[...large,widget];setLarge(next);persist(widgets,next)}}>{large.includes(widget)?<Minimize2 size={14}/>:<Maximize2 size={14}/>}</button></header>{widget==="资产打分"?<ScoreBoard data={data} history={history}/>:widget==="宏观象限"?<RegimeBoard data={data}/>:widget==="相关性"?<CorrelationMatrix history={history} days={20}/>:widget==="事件日历"?<div className="event-stack">{eventRows(data).slice(0,4).map(item=><a href={item.source} target="_blank" rel="noreferrer" key={item.date+item.event}><time>{item.date.slice(5)}</time><span><strong>{item.event}</strong><small>{item.assets}</small></span></a>)}</div>:widget==="AI链条"?<div className="rotation-bars">{aiChainRows(data).slice(0,6).map(item=><div key={item.group}><span>{item.group}</span><div><i className="up" style={{width:`${item.strength}%`}}/></div><strong>{item.strength}</strong></div>)}</div>:<MarketsTable data={data} history={history.slice(0,4)}/>}</section>)}</div>
  </>
}

function ReportPage({data,history}:{data:DashboardData;history:HistorySeries[]}){const scores=assetScores(data,history),regime=macroRegime(data),top=scores.slice().sort((a,b)=>b.score-a.score).slice(0,3),chain=aiChainRows(data).slice().sort((a,b)=>b.strength-a.strength),events=eventRows(data),chainText=chain.length?chain.slice(0,4).map(i=>`${i.group}（强度${i.strength}）`).join("；"):"暂无有效链条行情",eventText=events.length?events.slice(0,4).map(i=>`${i.date} ${i.event}`).join("、"):"未来180天暂无已公布的高影响事件",report=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>今日资产配置晨报</title><style>body{font-family:Arial,'Microsoft YaHei';max-width:980px;margin:40px auto;color:#23191b}h1{color:#9d1735;border-bottom:3px solid #9d1735;padding-bottom:16px}h2{margin-top:30px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ddd;padding:10px;text-align:left}.note{padding:14px;background:#f7f3f4}</style><h1>今日资产配置晨报</h1><p>生成时间：${new Date().toLocaleString("zh-CN")}</p><h2>核心结论</h2><p class="note">当前宏观象限：${regime.quadrant}。优先关注：${regime.focus}。相对回避：${regime.avoid}。</p><h2>资产打分</h2><table><tr><th>资产</th><th>分数</th><th>判断</th><th>驱动</th></tr>${scores.map(i=>`<tr><td>${i.asset}</td><td>${i.score}</td><td>${i.view}</td><td>${i.driver}</td></tr>`).join("")}</table><h2>AI产业链</h2><p>${chainText}</p><h2>风险提示</h2><p>${eventText}</p></html>`;const download=()=>{const blob=new Blob([report],{type:"text/html;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`资产配置晨报_${new Date().toISOString().slice(0,10)}.html`;a.click();URL.revokeObjectURL(url)};const print=()=>{const win=window.open("","_blank");if(win){win.document.write(report);win.document.close();win.print()}};return <div className="page-grid"><Panel title="晨报预览" kicker="DAILY BRIEF" className="span-2"><article className="report-sheet"><header><span>{new Date().toLocaleDateString("zh-CN")}</span><h2>今日资产配置晨报</h2><p>宏观 · 跨资产 · AI产业链 · 风险事件</p></header><h3>一、核心配置结论</h3><p>当前处于<strong>{regime.quadrant}</strong>象限，建议优先关注<strong>{regime.focus}</strong>，相对回避{regime.avoid}。</p><h3>二、资产强弱排序</h3>{top.map((item,index)=><div className="report-rank" key={item.asset}><em>0{index+1}</em><strong>{item.asset}</strong><span>{item.score} / 100 · {item.view}</span></div>)}<h3>三、AI链条</h3><p>{chain.length?`${chain.slice(0,3).map(item=>`${item.group}（${item.strength}）`).join("、")}处于相对强势。`:chainText}</p><h3>四、风险事件</h3><p>{eventText}。</p></article></Panel><Panel title="导出" kicker="EXPORT"><div className="export-actions"><button onClick={download}><Download size={17}/>下载 HTML</button><button onClick={print}><ExternalLink size={17}/>打印 / 导出PDF</button></div><p className="large-note">PDF通过浏览器打印窗口生成，可选择“另存为 PDF”。</p></Panel></div>}

export function TerminalDashboard({section="overview"}:{section?:string}){
  const[data,setData]=useState<DashboardData>(seedData as DashboardData),[query,setQuery]=useState(""),[favorites,setFavorites]=useState<FavoriteItem[]>([]),[favoriteNotice,setFavoriteNotice]=useState("");
  useEffect(()=>{const url=new URL("data/latest.json",document.baseURI);fetch(url).then(response=>response.ok?response.json():Promise.reject()).then(payload=>setData(payload as DashboardData)).catch(()=>{})},[]);
  useEffect(()=>{setFavorites(loadFavorites())},[]);
  useEffect(()=>{if(!favoriteNotice)return;const timer=window.setTimeout(()=>setFavoriteNotice(""),2200);return()=>window.clearTimeout(timer)},[favoriteNotice]);
  const history=(data.market_history?.length??0)>=6?data.market_history!:fallbackHistory;
  const suggestions=useMemo(()=>query?favoriteCatalog.filter(item=>favoriteMatches(item,query)).slice(0,8):[],[query]);
  const[title,subtitle]=sectionTitles[section]??sectionTitles.overview,generated=data.generated_at?new Date(data.generated_at).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai"}):"缓存数据";
  const currentFavorite=findFavorite(`page:${section}`)??{id:`page:${section}`,label:title,code:"分析页",category:"研究模块",href:navigation.find(item=>item.key===section)?.href??"/",keywords:`${title} ${subtitle}`};
  const isCurrentFavorite=favorites.some(item=>item.id===currentFavorite.id);
  const saveFavorites=(next:FavoriteItem[])=>{setFavorites(next);localStorage.setItem(FAVORITES_KEY,JSON.stringify(next))};
  const addFavorite=(item:FavoriteItem)=>{if(favorites.some(saved=>saved.id===item.id)){setFavoriteNotice(`${item.label} 已在收藏中`);return}saveFavorites([...favorites,item]);setFavoriteNotice(`已收藏：${item.label}`)};
  const removeFavorite=(id:string)=>{const item=favorites.find(saved=>saved.id===id);saveFavorites(favorites.filter(saved=>saved.id!==id));if(item)setFavoriteNotice(`已取消收藏：${item.label}`)};
  const toggleCurrentFavorite=()=>isCurrentFavorite?removeFavorite(currentFavorite.id):addFavorite(currentFavorite);
  let content:React.ReactNode;
  if(section==="allocation")content=<AllocationPage data={data} history={history}/>;
  else if(section==="regime")content=<RegimePage data={data}/>;
  else if(section==="correlation")content=<CorrelationPage history={history}/>;
  else if(section==="markets")content=<div className="page-grid"><Panel title="全球市场轮动表" kicker="GLOBAL MARKET" className="span-3"><MarketsTable data={data} history={history}/></Panel></div>;
  else if(section==="etf-flows")content=<EtfPage data={data} history={history}/>;
  else if(section==="ai-chain")content=<AiPage data={data}/>;
  else if(section==="calendar")content=<CalendarPage data={data}/>;
  else if(section==="research")content=<ResearchPage data={data}/>;
  else if(section==="workspace")content=<WorkspacePage data={data} history={history} favorites={favorites} onAddFavorite={addFavorite} onRemoveFavorite={removeFavorite}/>;
  else if(section==="report")content=<ReportPage data={data} history={history}/>;
  else content=<OverviewPage data={data} history={history}/>;
  return <div className="terminal-shell"><aside className="sidebar"><Link href="/" className="brand"><span>AA</span><div><strong>Asset Allocation</strong><small>Research Terminal</small></div></Link><nav>{navigation.map((item,index)=><Link className={section===item.key?"active":""} href={item.href} key={item.key}><span>{String(index+1).padStart(2,"0")}</span>{item.label}</Link>)}</nav><div className="sidebar-foot"><div><i className="online"/><span>数据服务正常</span></div><small>四小时自动更新</small></div></aside><main className="terminal-main"><header className="topbar"><div className="search-box"><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索 NVDA、黄金、US10Y、FOMC..."/>{suggestions.length>0&&<div className="suggestions">{suggestions.map(item=><Link href={item.href} onClick={()=>setQuery("")} key={item.id}><Search size={13}/><span><strong>{item.label}</strong><small>{item.code} · {item.category}</small></span><ChevronRight size={13}/></Link>)}</div>}</div><div className="top-actions"><span><RefreshCw size={14}/>更新于 {generated}</span><Link href="/workspace" aria-label="我的工作区"><LayoutDashboard size={17}/></Link><Link href="/report" aria-label="导出晨报"><Download size={17}/></Link></div></header><div className="page-header"><div><span>GLOBAL ALLOCATION / {section.toUpperCase()}</span><h1>{title}</h1><p>{subtitle}</p></div><div className="header-tags"><StatusPill kind="positive">公开数据</StatusPill><StatusPill>4H 更新</StatusPill><button className={isCurrentFavorite?"favorite-active":""} aria-pressed={isCurrentFavorite} aria-label={isCurrentFavorite?"取消收藏当前页面":"收藏当前页面"} title={isCurrentFavorite?"取消收藏当前页面":"收藏当前页面"} onClick={toggleCurrentFavorite}><Star size={16} fill={isCurrentFavorite?"currentColor":"none"}/></button></div></div><div className="terminal-content">{content}</div></main>{favoriteNotice&&<div className="favorite-notice" role="status"><Star size={15} fill="currentColor"/>{favoriteNotice}</div>}</div>
}
